apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pvnm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pvnm
    app.kubernetes.io/part-of: tkwch-fix-0075-0044-app
  name: devfile-sample-pvnm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pvnm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pvnm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0044-tenant/tkwch-fix-0075-0044-app/devfile-sample-pvnm@sha256:1e24d151c2d81b8d0e3ec6186ef53b26e693163b35ff4a5bf96352cb0b12a4b2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
